# =============================================================================
# Variables — only cloudflare_api_token is required
#
# Values that Cloudflare itself generates (OIDC client credentials, the TURN
# key, the session cookie secret) are NOT variables: they are read off the
# resources that create them. See access.tf, turn.tf and main.tf.
# =============================================================================

variable "cloudflare_api_token" {
  description = "Cloudflare API token with Workers, D1, R2, Calls, Access, and DNS permissions."
  type        = string
  sensitive   = true
}

variable "cloudflare_zone_id" {
  description = "Zone hosting the R2 CDN hostname. Required only when r2_cdn_hostname is set."
  type        = string
  default     = ""
}

variable "worker_name" {
  description = "Name of the Cloudflare Worker."
  type        = string
  default     = "jetkvm-cloud-api"
}

variable "workers_dev_subdomain" {
  description = "The account's workers.dev subdomain (e.g. \"acme\" for acme.workers.dev). Only used to render worker_subdomain_url; the API exposes no data source for it."
  type        = string
  default     = ""
}

variable "d1_database_name" {
  description = "Name of the D1 database."
  type        = string
  default     = "jetkvm-cloud-api"
}

variable "r2_bucket_name" {
  description = "Name of the R2 bucket for firmware releases."
  type        = string
  default     = "jetkvm-releases"
}

variable "r2_bucket_location" {
  description = "Location hint for the R2 bucket (apac, eeur, enam, weur, wnam, oc)."
  type        = string
  default     = "wnam"
}

# -----------------------------------------------------------------------------
# Hostnames — bare hostnames, no scheme. The Worker receives https:// URLs.
# -----------------------------------------------------------------------------

variable "api_hostname" {
  description = "Public hostname of this API, e.g. api.jetkvm.com. Required when enable_access = true."
  type        = string
  default     = ""

  validation {
    condition     = !can(regex("^https?://", var.api_hostname))
    error_message = "api_hostname must be a bare hostname without a scheme."
  }
}

variable "app_hostname" {
  description = "Frontend app hostname, e.g. app.jetkvm.com."
  type        = string
  default     = ""

  validation {
    condition     = !can(regex("^https?://", var.app_hostname))
    error_message = "app_hostname must be a bare hostname without a scheme."
  }
}

variable "r2_cdn_hostname" {
  description = "Public hostname serving R2 release artifacts, e.g. releases.jetkvm.com. Empty disables the R2 custom domain."
  type        = string
  default     = ""
}

variable "cors_origins" {
  description = "Comma-separated list of allowed CORS origins."
  type        = string
  default     = ""
}

variable "allowed_identities" {
  description = "Comma-separated email allowlist enforced by the Worker. Empty allows any authenticated identity."
  type        = string
  default     = ""
}

# -----------------------------------------------------------------------------
# Zero Trust Access
# -----------------------------------------------------------------------------

variable "enable_access" {
  description = "Create a Cloudflare Access SaaS application and use Access as the Worker's OIDC provider."
  type        = bool
  default     = true
}

variable "access_app_name" {
  description = "Name of the Access application."
  type        = string
  default     = "JetKVM Cloud API"
}

variable "access_session_duration" {
  description = "How long Access tokens issued for the application remain valid."
  type        = string
  default     = "24h"
}

variable "access_allowed_emails" {
  description = "Emails allowed to log in through Access. Combined with access_allowed_email_domains; if both are empty, everyone may log in."
  type        = list(string)
  default     = []
}

variable "access_allowed_email_domains" {
  description = "Email domains allowed to log in through Access, e.g. [\"jetkvm.com\"]."
  type        = list(string)
  default     = []
}

# -----------------------------------------------------------------------------
# External OIDC provider — used only when enable_access = false.
# When enable_access = true these are generated by the Access application.
# -----------------------------------------------------------------------------

variable "oidc_issuer" {
  description = "OIDC issuer URL of an external IdP. Required when enable_access = false."
  type        = string
  default     = ""

  validation {
    condition     = var.enable_access || var.oidc_issuer != ""
    error_message = "oidc_issuer is required when enable_access = false."
  }
}

variable "oidc_client_id" {
  description = "OIDC client ID of an external IdP. Required when enable_access = false."
  type        = string
  default     = ""

  validation {
    condition     = var.enable_access || var.oidc_client_id != ""
    error_message = "oidc_client_id is required when enable_access = false."
  }
}

variable "oidc_client_secret" {
  description = "OIDC client secret of an external IdP. Required when enable_access = false."
  type        = string
  default     = ""
  sensitive   = true

  validation {
    condition     = var.enable_access || var.oidc_client_secret != ""
    error_message = "oidc_client_secret is required when enable_access = false."
  }
}

# -----------------------------------------------------------------------------
# Cloudflare Calls (TURN)
# -----------------------------------------------------------------------------

variable "turn_app_name" {
  description = "Name of the Cloudflare Calls TURN key."
  type        = string
  default     = "jetkvm-cloud-api"
}

variable "create_turn_key" {
  description = "Mint a new Cloudflare Calls TURN key via POST. Set true for exactly one apply, then back to false — the data source re-POSTs on every read and would otherwise mint a key each plan. See turn.tf."
  type        = bool
  default     = false
}

# -----------------------------------------------------------------------------
# Worker build / deploy
# -----------------------------------------------------------------------------

variable "worker_dist_dir" {
  description = "Path to the compiled Worker output directory (relative to terraform/)."
  type        = string
  default     = "../dist"
}

variable "app_worker_name" {
  description = "Name of the static-assets Worker serving the UI."
  type        = string
  default     = "jetkvm-cloud-app"
}

variable "app_dist_dir" {
  description = "Path to the built JetKVM UI bundle (relative to terraform/). See app.tf."
  type        = string
  default     = "../dist-ui"
}

variable "app_version_message" {
  description = "Human-readable annotation for the deployed UI version."
  type        = string
  default     = "UI bundle deployed via Terraform"
}

variable "worker_version_message" {
  description = "Human-readable annotation for the deployed Worker version."
  type        = string
  default     = "Deployed via Terraform"
}
